export const ADD_NEW_SUPPLIER_START = "ADD_NEW_SUPPLIER_START";
export const ADD_NEW_SUPPLIER_SUCCESS = "ADD_NEW_SUPPLIER_SUCCESS";
export const ADD_NEW_SUPPLIER_FAILED = "ADD_NEW_SUPPLIER_FAILED";

// get All supliers list
export const GET_ALL_SUPLIER_START = "GET_ALL_SUPLIER_START";
export const GET_ALL_SUPLIER_SUCCESS = "GET_ALL_SUPLIER_SUCCESS";
export const GET_ALL_SUPLIER_FAILED = "GET_ALL_SUPLIER_FAILED";

export const ADD_NEW_CATEGORY_START = "ADD_NEW_CATEGORY_START";
export const ADD_NEW_CATEGORY_SUCCESS = "ADD_NEW_CATEGORY_SUCCESS";
export const ADD_NEW_CATEGORY_FAILED = "ADD_NEW_CATEGORY_FAILED";

export const GET_ALL_CATEGORY_START = "GET_ALL_CATEGORY_START";
export const GET_ALL_CATEGORY_SUCCESS = "GET_ALL_CATEGORY_SUCCESS";
export const GET_ALL_CATEGORY_FAILED = "GET_ALL_CATEGORY_FAILED";

export const SWITCH_SCREENMODE = "SWITCH_SCREENMODE";

export const PURCHASE_ENTRY_START = "PURCHASE_ENTRY_START";
export const PURCHASE_ENTRY_SUCCESS = "PURCHASE_ENTRY_SUCCESS";
export const PURCHASE_ENTRY_FAILED = "PURCHASE_ENTRY_FAILED";

export const GET_PRODUCT_BY_BARCODE_START = "GET_PRODUCT_BY_BARCODE_START";
export const GET_PRODUCT_BY_BARCODE_SUCCESS = "GET_PRODUCT_BY_BARCODE_SUCCESS";
export const GET_PRODUCT_BY_BARCODE_FAILED = "GET_PRODUCT_BY_BARCODE_FAILED";

export const GET_CUSTOMER_BY_NUMBER_FOR_SALE_START =
  "GET_CUSTOMER_BY_NUMBER_FOR_SALE_START";
export const GET_CUSTOMER_BY_NUMBER_FOR_SALE_SUCCESS =
  "GET_CUSTOMER_BY_NUMBER_FOR_SALE_SUCCESS";
export const GET_CUSTOMER_BY_NUMBER_FOR_SALE_FAILED =
  "GET_CUSTOMER_BY_NUMBER_FOR_SALE_FAILED";

export const ADD_NEW_CUSTOMER_START = "ADD_NEW_CUSTOMER_START";
export const ADD_NEW_CUSTOMER_SUCCESS = "ADD_NEW_CUSTOMER_SUCCESS";
export const ADD_NEW_CUSTOMER_FAILED = "ADD_NEW_CUSTOMER_FAILED";

export const ADD_NEW_SALESMAN_START = "ADD_NEW_SALESMAN_START";
export const ADD_NEW_SALESMAN_SUCCESS = "ADD_NEW_SALESMAN_SUCCESS";
export const ADD_NEW_SALESMAN_FAILED = "ADD_NEW_SALESMAN_FAILED";

export const GENRATE_BILL_START = "GENRATE_BILL_START";
export const GENRATE_BILL_SUCCESS = "GENRATE_BILL_SUCCESS";
export const GENRATE_BILL_FAILED = "GENRATE_BILL_FAILED";

export const SUPPLIER_STATE = "SUPPLIER_STATE";
export const SALESMAN_STATE = "SALESMAN_STATE";
export const CATEGORY_STATE = "CATEGORY_STATE";
export const CUSTOMER_STATE = "CUSTOMER_STATE";
export const REPORT_STATE = "REPORT_STATE";
export const PRODUCT_STATE = "PRODUCT_STATE";
export const LOCATION_STATE = "LOCATION_STATE";

export const GET_ALL_PRODUCT_STRAT = "GET_ALL_PRODUCT_STRAT";
export const GET_ALL_PRODUCT_SUCCESS = "GET_ALL_PRODUCT_SUCCESS";
export const GET_ALL_PRODUCT_FAILED = "GET_ALL_PRODUCT_FAILED";

export const GET_ALL_SALESMAN_STRAT = "GET_ALL_SALESMAN_STRAT";
export const GET_ALL_SALESMAN_SUCCESS = "GET_ALL_SALESMAN_SUCCESS";
export const GET_ALL_SALESMAN_FAILED = "GET_ALL_SALESMAN_FAILED";

export const GET_ALL_CUSTOMER_STRAT = "GET_ALL_CUSTOMER_STRAT";
export const GET_ALL_CUSTOMER_SUCCESS = "GET_ALL_CUSTOMER_SUCCESS";
export const GET_ALL_CUSTOMER_FAILED = "GET_ALL_CUSTOMER_FAILED";

export const GET_SUPPLIER_INVOICE_STRAT = "GET_SUPPLIER_INVOICE_STRAT";
export const GET_SUPPLIER_INVOICE_SUCCESS = "GET_SUPPLIER_INVOICE_SUCCESS";
export const GET_SUPPLIER_INVOICE_FAILED = "GET_SUPPLIER_INVOICE_FAILED";

export const GET_BILL_REPORT_STRAT = "GET_BILL_REPORT_STRAT";
export const GET_BILL_REPORT_SUCCESS = "GET_BILL_REPORT_SUCCESS";
export const GET_BILL_REPORT_FAILED = "GET_BILL_REPORT_FAILED";

export const GET_BILL_BY_BARCODE_STRAT = "GET_BILL_BY_BARCODE_STRAT";
export const GET_BILL_BY_BARCODE_SUCCESS = "GET_BILL_BY_BARCODE_SUCCESS";
export const GET_BILL_BY_BARCODE_FAILED = "GET_BILL_BY_BARCODE_FAILED";

export const GET_CATEGORY_BARCODE_STRAT = "GET_CATEGORY_BARCODE_STRAT";
export const GET_CATEGORY_BARCODE_SUCCESS = "GET_CATEGORY_BARCODE_SUCCESS";
export const GET_CATEGORY_BARCODE_FAILED = "GET_CATEGORY_BARCODE_FAILED ";
export const GET_CATEGORY_BARCODE_CLEAR = "GET_CATEGORY_BARCODE_CLEAR";

export const GET_CATEGORY_BARCODE_NAME_START =
  "GET_CATEGORY_BARCODE_NAME_START";
export const GET_CATEGORY_BARCODE_NAME_SUCCESS =
  "GET_CATEGORY_BARCODE_NAME_SUCCESS";
export const GET_CATEGORY_BARCODE_NAME_FAILED =
  "GET_CATEGORY_BARCODE_NAME_FAILED";

export const GET_WEEKLY_CHART_START = "GET_WEEKLY_CHART_START";
export const GET_WEEKLY_CHART_SUCCESS = "GET_WEEKLY_CHART_SUCCESS";
export const GET_WEEKLY_CHART_FAILED = "GET_WEEKLY_CHART_FAILED";

export const GET_PREVIOUS_WEEKLY_CHART_START =
  "GET_PREVIOUS_WEEKLY_CHART_START";
export const GET_PREVIOUS_WEEKLY_CHART_SUCCESS =
  "GET_PREVIOUS_WEEKLY_CHART_SUCCESS";
export const GET_PREVIOUS_WEEKLY_CHART_FAILED =
  "GET_PREVIOUS_WEEKLY_CHART_FAILED";

export const GET_SALESMAN_REPORT_STRAT = "GET_SALESMAN_REPORT_STRAT";
export const GET_SALESMAN_REPORT_SUCCESS = "GET_SALESMAN_REPORT_SUCCESS";
export const GET_SALESMAN_REPORT_FAILED = "GET_SALESMAN_REPORT_FAILED";

export const EXCHANGE_BILL_START = "EXCHANGE_BILL_START";
export const EXCHANGE_BILL_SUCCESS = "EXCHANGE_BILL_SUCCESS";
export const EXCHANGE_BILL_FAILED = "EXCHANGE_BILL_FAILED";

export const GET_EXCHANGE_BILL_BY_ID_FOR_SALE_START =
  "GET_EXCHANGE_BILL_BY_ID_FOR_SALE_START";
export const GET_EXCHANGE_BILL_BY_ID_FOR_SALE_SUCCESS =
  "GET_EXCHANGE_BILL_BY_ID_FOR_SALE_SUCCESS";
export const GET_EXCHANGE_BILL_BY_ID_FOR_SALE_FAILED =
  "GET_EXCHANGE_BILL_BY_ID_FOR_SALE_FAILED";

export const GENRATE_BILL_CLEAR = "GENRATE_BILL_CLEAR";

export const GET_BILL_BY_PRODUCT_BARCODE_STRAT =
  "GET_BILL_BY_PRODUCT_BARCODE_STRAT";
export const GET_BILL_BY_PRODUCT_BARCODE_SUCCESS =
  "GET_BILL_BY_PRODUCT_BARCODE_SUCCESS";
export const GET_BILL_BY_PRODUCT_BARCODE_FAILED =
  "GET_BILL_BY_PRODUCT_BARCODE_FAILED";

export const ADD_NEW_LOCATION_START = "ADD_NEW_LOCATION_START";
export const ADD_NEW_LOCATION_SUCCESS = "ADD_NEW_LOCATION_SUCCESS";
export const ADD_NEW_LOCATION_FAILED = "ADD_NEW_LOCATION_FAILED";
