export const ADD_NEW_SUPPLIER_START = "ADD_NEW_SUPPLIER_START";
export const ADD_NEW_SUPPLIER_SUCCESS = "ADD_NEW_SUPPLIER_SUCCESS";
export const ADD_NEW_SUPPLIER_FAILED = "ADD_NEW_SUPPLIER_FAILED";

// get All supliers list
export const GET_ALL_SUPLIER_START = "GET_ALL_SUPLIER_START";
export const GET_ALL_SUPLIER_SUCCESS = "GET_ALL_SUPLIER_SUCCESS";
export const GET_ALL_SUPLIER_FAILED = "GET_ALL_SUPLIER_FAILED";

export const ADD_NEW_CATEGORY_START = "ADD_NEW_CATEGORY_START";
export const ADD_NEW_CATEGORY_SUCCESS = "ADD_NEW_CATEGORY_SUCCESS";
export const ADD_NEW_CATEGORY_FAILED = "ADD_NEW_CATEGORY_FAILED";

export const GET_ALL_CATEGORY_START = "GET_ALL_CATEGORY_START";
export const GET_ALL_CATEGORY_SUCCESS = "GET_ALL_CATEGORY_SUCCESS";
export const GET_ALL_CATEGORY_FAILED = "GET_ALL_CATEGORY_FAILED";

export const SWITCH_SCREENMODE = "SWITCH_SCREENMODE";

export const PURCHASE_ENTRY_START = "PURCHASE_ENTRY_START";
export const PURCHASE_ENTRY_SUCCESS = "PURCHASE_ENTRY_SUCCESS";
export const PURCHASE_ENTRY_FAILED = "PURCHASE_ENTRY_FAILED";
