export const ADD_NEW_SUPPLIER_START = "ADD_NEW_SUPPLIER_START";
export const ADD_NEW_SUPPLIER_SUCCESS = "ADD_NEW_SUPPLIER_SUCCESS";
export const ADD_NEW_SUPPLIER_FAILED = "ADD_NEW_SUPPLIER_FAILED";

// get All supliers list
export const GET_ALL_SUPLIER_START = "GET_ALL_SUPLIER_START";
export const GET_ALL_SUPLIER_SUCCESS = "GET_ALL_SUPLIER_SUCCESS";
export const GET_ALL_SUPLIER_FAILED = "GET_ALL_SUPLIER_FAILED";

export const ADD_NEW_CATEGORY_START = "ADD_NEW_CATEGORY_START";
export const ADD_NEW_CATEGORY_SUCCESS = "ADD_NEW_CATEGORY_SUCCESS";
export const ADD_NEW_CATEGORY_FAILED = "ADD_NEW_CATEGORY_FAILED";

export const GET_ALL_CATEGORY_START = "GET_ALL_CATEGORY_START";
export const GET_ALL_CATEGORY_SUCCESS = "GET_ALL_CATEGORY_SUCCESS";
export const GET_ALL_CATEGORY_FAILED = "GET_ALL_CATEGORY_FAILED";

export const SWITCH_SCREENMODE = "SWITCH_SCREENMODE";

export const PURCHASE_ENTRY_START = "PURCHASE_ENTRY_START";
export const PURCHASE_ENTRY_SUCCESS = "PURCHASE_ENTRY_SUCCESS";
export const PURCHASE_ENTRY_FAILED = "PURCHASE_ENTRY_FAILED";

export const GET_PRODUCT_BY_BARCODE_START = "GET_PRODUCT_BY_BARCODE_START";
export const GET_PRODUCT_BY_BARCODE_SUCCESS = "GET_PRODUCT_BY_BARCODE_SUCCESS";
export const GET_PRODUCT_BY_BARCODE_FAILED = "GET_PRODUCT_BY_BARCODE_FAILED";

export const GET_CUSTOMER_BY_NUMBER_FOR_SALE_START =
  "GET_CUSTOMER_BY_NUMBER_FOR_SALE_START";
export const GET_CUSTOMER_BY_NUMBER_FOR_SALE_SUCCESS =
  "GET_CUSTOMER_BY_NUMBER_FOR_SALE_SUCCESS";
export const GET_CUSTOMER_BY_NUMBER_FOR_SALE_FAILED =
  "GET_CUSTOMER_BY_NUMBER_FOR_SALE_FAILED";

export const ADD_NEW_CUSTOMER_START = "ADD_NEW_CUSTOMER_START";
export const ADD_NEW_CUSTOMER_SUCCESS = "ADD_NEW_CUSTOMER_SUCCESS";
export const ADD_NEW_CUSTOMER_FAILED = "ADD_NEW_CUSTOMER_FAILED";

export const ADD_NEW_SALESMAN_START = "ADD_NEW_SALESMAN_START";
export const ADD_NEW_SALESMAN_SUCCESS = "ADD_NEW_SALESMAN_SUCCESS";
export const ADD_NEW_SALESMAN_FAILED = "ADD_NEW_SALESMAN_FAILED";

export const GENRATE_BILL_START = "GENRATE_BILL_START";
export const GENRATE_BILL_SUCCESS = "GENRATE_BILL_SUCCESS";
export const GENRATE_BILL_FAILED = "GENRATE_BILL_FAILED";

export const SUPPLIER_STATE = "SUPPLIER_STATE";
export const SALESMAN_STATE = "SALESMAN_STATE";
export const CATEGORY_STATE = "CATEGORY_STATE";
